apiVersion: v1
kind: Service
metadata:
  name: yolo-frontend-service
  labels:
    app: yolo-frontend-k8s
spec:
  selector:
    app: yolo-frontend-deployment
    tier: frontend
  type: ClusterIP
  ports:
  - protocol: "TCP"
    port: 3000
    targetPort: 3000
