apiVersion: apps/v1
kind: Deployment
metadata:
  name: yolo-backend-deployment
spec:
  selector:
    matchLabels:
      app: yolo
      tier: backend
      track: stable
  replicas: 2
  template:
    metadata:
      labels:
        app: yolo
        tier: backend
        track: stable
  spec:
    containers:
      - name: yolo-backend
        image: tonzi/yolo-backend:1.0.0
        ports:
          - containerPort: 5000
