apiVersion: apps/v1
kind: Deployment
metadata:
  name: yolo-frontend-deployment
spec:
  selector:
    matchLabels:
      app: yolo
      tier: frontend
      track: stable
  replicas: 2
  template:
    metadata:
      labels:
        app: yolo
        tier: frontend
        track: stable
  spec:
    containers:
      - name: yolo-frontend
        image: tonzi/yolo-frontend:1.0.0
        ports:
          - containerPort: 3000
            env:
              - name: PORT
                value: "3000"