apiVersion: v1
kind: Service
metadata:
  name: yolo-frontend-service
spec:
  selector:
    app: yolo
    tier: frontend
  type: LoadBalancer
  ports:
  - protocol: "TCP"
    port: 3000
    targetPort: 3000
    nodePort: 30000
