version: '3'
services:
  frontend:
    image: tonzi/yolo-client:1.0.1
    ports:
      - 3000:3000
    stdin_open: true
    depends_on:
      - backend
    networks:
      yolo-network:
        ipv4_address: 172.20.0.10
  backend:
    image: tonzi/yolo-backend:1.0.1
    ports:
      - 5000:5000
    environment:
      MONGODB_URI: 'mongodb://admin:admin@172.20.0.1:27017/'
    volumes:
      - ./backend:/app
    depends_on:
      - database
    networks:
      yolo-network:
        ipv4_address: 172.20.0.20
  database:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    ports:
      - 27017:27017
    volumes:
      - yolo-vol:/data/db
    networks:
      yolo-network:
        ipv4_address: 172.20.0.100
networks:
  yolo-network:
    ipam:
      driver: default
      config:
        - subnet: 172.20.0.0/16
volumes:
  yolo-vol: