---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: yolo-backend-deployment
  labels:
    app: yolo-backend-k8s
spec:
  selector:
    matchLabels:
      app: yolo-backend-k8s
      tier: backend
      track: stable
  replicas: 2
  template:
    metadata:
      labels:
        app: yolo-backend-k8s
        tier: backend
        track: stable
    spec:
      containers:
        - name: yolo-backend
          image: "tonzi/yolo-backend:1.0.1"
          ports:
          - containerPort: 5000
          env:
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: yolo-backend-config
                  key: PORT
            - name: MONGODB_URI
              valueFrom:
                secretKeyRef:
                  name: yolo-backend-secret
                  key: MONGODB_URI
          resources:
            requests:
              memory: "1Gi"
              cpu: "500m"
            limits:
              memory: "1Gi"
              cpu: "500m"