apiVersion: v1
kind: Secret
metadata:
  name: yolo-database-secret
  labels:
    app: yolo-backend-mongodb-url
data:
  # MONGODB_URI: "bW9uZ29kYitzcnY6Ly95b2xvOnlvbG9LOHN1ZG9Vc2VyQHlvbG8tazhzLWNsdXN0ZXIuaDdzMHVvZC5tb25nb2RiLm5ldC95b2xvbXk="
  MONGODB_URI: "bW9uZ29kYjovL2FkbWluOmFkbWluQDEwLjI0NC4wLjQwOjI3MDE3Lw=="
  