apiVersion: v1
kind: Service
metadata:
  name: yolo-backend-service
  labels:
    app: yolo-backend-k8s
spec:
  selector:
    app: yolo-backend-deployment
    tier: backend
  type: ClusterIP
  ports:
    - protocol: "TCP"
      port: 5000
      targetPort: 5000
      nodePort: 31000
  