---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: yolo-database-k8s
  labels:
    app: yolo-database-k8s
spec:
  serviceName: yolo-database-k8s
  replicas: 1
  selector:
    matchLabels:
      app: yolo-database-k8s
      tier: database
  template:
    metadata:
      labels:
        app: yolo-database-k8s
        tier: database
    spec:
      containers:
        - name: yolo-database
          image: "mongo"
          imagePullPolicy: Always
          ports:
          - containerPort: 27017
          env:
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: yolo-database-config
                  key: PORT
            - name: MONGO_INITDB_ROOT_USERNAME
              valueFrom:
                secretKeyRef:
                  name: yolo-database-secret
                  key: MONGO_INITDB_ROOT_USERNAME
            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: yolo-database-secret
                  key: MONGO_INITDB_ROOT_PASSWORD
          resources:
            requests:
              memory: "1Gi"
              cpu: "256m"
            limits:
              memory: "1Gi"
              cpu: "256m"
          volumeMounts:
          - name: "mongo-data-dir"
            mountPath: "/data/db"
      volumes:
        - name: "mongo-data-dir"
          persistentVolumeClaim:
            claimName: "mongodb-pvc"