apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: "mongodb-pvc"
  labels:
    app: "yolo-database-k8s"
spec:
  accessModes:
    - ReadWriteOnce 
  resources:
    requests:
      storage: 1Gi
  storageClassName: gp2