  apiVersion: "v1"
  kind: Service
  metadata: 
    name: yolo-database-k8s
    labels: 
      app: yolo-database-k8s
  spec: 
    externalTrafficPolicy: Local
    ports: 
      - name: "mongodb"
        port: 27017
        nodePort: 30332
    type: "NodePort"
    selector: 
      app: "yolo-database-k8s"